# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
df = pd.read_excel('Folds5x2_pp.xlsx')
df

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [ ]:
x = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [ ]:
print(x)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [ ]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation= 'linear')) #activation='sigmoid' and relu are used for classification

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

### Training the ANN model on the Training set

In [ ]:
ann.fit(x_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 205548.8594
Epoch 2/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 199887.4375
Epoch 3/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 194193.0312
Epoch 4/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 189258.3594
Epoch 5/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 183028.4844
Epoch 6/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 177437.5469
Epoch 7/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 171613.4062
Epoch 8/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 165824.2188
Epoch 9/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 160160.6562
Epoch 10/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 154258.2031
Epoch 11/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 148159.5938
Epoch 12/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 142820.2812
Epoch 13/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 136905.2812
Epoch 14/100
240/240 ━━━━━━━━━━━━━━━━━━━━ 1s 1m

### Predicting the results of the Test set

In [ ]:
y_pred = ann.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

60/60 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step
[[454.53 431.23]
 [454.53 460.01]
 [454.53 461.14]
 ...
 [454.53 473.26]
 [454.53 438.  ]
 [454.53 463.28]]


In [ ]:
# acuraccy score


-2.6025290784215116e-05